BEGIN TRANSACTION;
INSERT OR IGNORE INTO Category (category, topic_header, subcategory, insight_subject) VALUES ('Dating', 'Lifestyle', 'Communication', 'Conflict resolution');
INSERT OR IGNORE INTO Category (category, topic_header, subcategory, insight_subject) VALUES ('Dating', 'Lifestyle', 'Communication', 'Conversation medium');
INSERT OR IGNORE INTO Category (category, topic_header, subcategory, insight_subject) VALUES ('Dating', 'Lifestyle', 'Communication', 'Directness');
INSERT OR IGNORE INTO Category (category, topic_header, subcategory, insight_subject) VALUES ('Dating', 'Personality', 'Dating expectations', 'Dating intention');
INSERT OR IGNORE INTO Category (category, topic_header, subcategory, insight_subject) VALUES ('Dating', '-', 'Romanticism', 'Love language');
INSERT OR IGNORE INTO Category (category, topic_header, subcategory, insight_subject) VALUES ('Dating', 'Lifestyle', 'Sex', 'Sex adventurousness');
INSERT OR IGNORE INTO Category (category, topic_header, subcategory, insight_subject) VALUES ('Dating', 'Lifestyle', 'Sex', 'Expectations around sex');
INSERT OR IGNORE INTO Category (category, topic_header, subcategory, insight_subject) VALUES ('Dating', 'Relationship expectations', 'Attitudes toward monogamy/polyamory', 'Attitudes toward monogamy/polyamory');
INSERT OR IGNORE INTO Category (category, topic_header, subcategory, insight_subject) VALUES ('Dating', 'Personality', 'Relationship expectations', 'Independence');
INSERT OR IGNORE INTO Category (category, topic_header, subcategory, insight_subject) VALUES ('Dating', 'Lifestyle', 'Interests', 'Creative date preferences');
INSERT OR IGNORE INTO Category (category, topic_header, subcategory, insight_subject) VALUES ('Dating', 'Lifestyle', 'Interests', 'Adventurousness');
INSERT OR IGNORE INTO Category (category, topic_header, subcategory, insight_subject) VALUES ('Dating', 'Lifestyle', 'Fitness & health', 'Exercise frequency');
INSERT OR IGNORE INTO Category (category, topic_header, subcategory, insight_subject) VALUES ('Dating', 'Lifestyle', 'Fitness & health', 'Health consciousness');
INSERT OR IGNORE INTO Category (category, topic_header, subcategory, insight_subject) VALUES ('Dating', 'Lifestyle', 'Food', 'Dietary preferences');
INSERT OR IGNORE INTO Category (category, topic_header, subcategory, insight_subject) VALUES ('Dating', 'Lifestyle', 'Pets', 'Pet preferences');
INSERT OR IGNORE INTO Category (category, topic_header, subcategory, insight_subject) VALUES ('Dating', 'Lifestyle', 'Travel', 'Travel frequency');
INSERT OR IGNORE INTO Category (category, topic_header, subcategory, insight_subject) VALUES ('Dating', 'Personality', 'Humor', 'Sense of humor');
INSERT OR IGNORE INTO Category (category, topic_header, subcategory, insight_subject) VALUES ('Dating', 'Personality', 'Emotional style', 'Emotional expressiveness');
INSERT OR IGNORE INTO Category (category, topic_header, subcategory, insight_subject) VALUES ('Dating', 'Personality', 'Communication style', 'Conflict style');
INSERT OR IGNORE INTO Category (category, topic_header, subcategory, insight_subject) VALUES ('Dating', 'Personality', 'Communication style', 'Listening style');
INSERT OR IGNORE INTO Category (category, topic_header, subcategory, insight_subject) VALUES ('Dating', 'Values', 'Politics', 'Political orientation');
INSERT OR IGNORE INTO Category (category, topic_header, subcategory, insight_subject) VALUES ('Dating', 'Values', 'Religion & spirituality', 'Religious beliefs');
INSERT OR IGNORE INTO Category (category, topic_header, subcategory, insight_subject) VALUES ('Dating', 'Lifestyle', 'Social habits', 'Party frequency');
INSERT OR IGNORE INTO Category (category, topic_header, subcategory, insight_subject) VALUES ('Dating', 'Lifestyle', 'Social habits', 'Introversion vs extroversion');
INSERT OR IGNORE INTO Category (category, topic_header, subcategory, insight_subject) VALUES ('Dating', 'Lifestyle', 'Social habits', 'Friend group size preference');
INSERT OR IGNORE INTO Category (category, topic_header, subcategory, insight_subject) VALUES ('Dating', 'Lifestyle', 'Media', 'Screen time');
INSERT OR IGNORE INTO Category (category, topic_header, subcategory, insight_subject) VALUES ('Dating', 'Lifestyle', 'Media', 'Favorite genres');
INSERT OR IGNORE INTO Category (category, topic_header, subcategory, insight_subject) VALUES ('Dating', 'Lifestyle', 'Music', 'Music taste');
INSERT OR IGNORE INTO Category (category, topic_header, subcategory, insight_subject) VALUES ('Dating', 'Lifestyle', 'Movies & TV', 'Binge-watching habits');
INSERT OR IGNORE INTO Category (category, topic_header, subcategory, insight_subject) VALUES ('Dating', 'Lifestyle', 'Books', 'Reading frequency');
INSERT OR IGNORE INTO Category (category, topic_header, subcategory, insight_subject) VALUES ('Dating', 'Lifestyle', 'Art & culture', 'Museum/gallery interest');
INSERT OR IGNORE INTO Category (category, topic_header, subcategory, insight_subject) VALUES ('Dating', 'Lifestyle', 'Food', 'Cooking frequency');
INSERT OR IGNORE INTO Category (category, topic_header, subcategory, insight_subject) VALUES ('Dating', 'Lifestyle', 'Food', 'Favorite cuisines');
INSERT OR IGNORE INTO Category (category, topic_header, subcategory, insight_subject) VALUES ('Dating', 'Lifestyle', 'Fitness & health', 'Morning person vs night owl');
INSERT OR IGNORE INTO Category (category, topic_header, subcategory, insight_subject) VALUES ('Dating', 'Lifestyle', 'Travel', 'Preferred travel style');
INSERT OR IGNORE INTO Category (category, topic_header, subcategory, insight_subject) VALUES ('Dating', 'Personality', 'Openness', 'Openness to new experiences');
INSERT OR IGNORE INTO Category (category, topic_header, subcategory, insight_subject) VALUES ('Dating', 'Personality', 'Conscientiousness', 'Organization style');
INSERT OR IGNORE INTO Category (category, topic_header, subcategory, insight_subject) VALUES ('Dating', 'Personality', 'Extraversion', 'Energy level');
INSERT OR IGNORE INTO Category (category, topic_header, subcategory, insight_subject) VALUES ('Dating', 'Personality', 'Agreeableness', 'Kindness level');
INSERT OR IGNORE INTO Category (category, topic_header, subcategory, insight_subject) VALUES ('Dating', 'Personality', 'Neuroticism', 'Stress management');
INSERT OR IGNORE INTO Category (category, topic_header, subcategory, insight_subject) VALUES ('Dating', 'Lifestyle', 'Life goals', 'Short-term goals');
INSERT OR IGNORE INTO Category (category, topic_header, subcategory, insight_subject) VALUES ('Dating', 'Lifestyle', 'Life goals', 'Long-term goals');
INSERT OR IGNORE INTO Category (category, topic_header, subcategory, insight_subject) VALUES ('Dating', 'Values', 'Family & upbringing', 'Family values');
INSERT OR IGNORE INTO Category (category, topic_header, subcategory, insight_subject) VALUES ('Dating', 'Values', 'Ethics', 'Moral alignment');
INSERT OR IGNORE INTO Category (category, topic_header, subcategory, insight_subject) VALUES ('Dating', 'Lifestyle', 'Communication', 'Tone sensitivity');
INSERT OR IGNORE INTO Category (category, topic_header, subcategory, insight_subject) VALUES ('Dating', 'Lifestyle', 'Personality', 'Trust style');
INSERT OR IGNORE INTO Category (category, topic_header, subcategory, insight_subject) VALUES ('Dating', 'Lifestyle', 'Lifestyle alignment', 'Routine compatibility');
COMMIT;
