export const CATEGORIES = [
  { category: 'Dating', topicHeader: 'Lifestyle', subcategory: 'Communication', insightSubject: 'Conflict resolution', expandedHints: undefined },
  { category: 'Dating', topicHeader: 'Lifestyle', subcategory: 'Communication', insightSubject: 'Conversation medium', expandedHints: undefined },
  { category: 'Dating', topicHeader: 'Lifestyle', subcategory: 'Communication', insightSubject: 'Directness', expandedHints: undefined },
  { category: 'Dating', topicHeader: 'Lifestyle', subcategory: 'Communication', insightSubject: 'Conversation medium', expandedHints: undefined },
  { category: 'Dating', topicHeader: 'Lifestyle', subcategory: 'Communication', insightSubject: 'Directness', expandedHints: undefined },
  { category: 'Dating', topicHeader: 'Personality', subcategory: 'Dating expectations', insightSubject: 'Dating intention', expandedHints: undefined },
  { category: 'Dating', topicHeader: '-', subcategory: 'Romanticism', insightSubject: 'Love language', expandedHints: undefined },
  { category: 'Dating', topicHeader: 'Lifestyle', subcategory: 'Sex', insightSubject: 'Sex adventurousness', expandedHints: undefined },
  { category: 'Dating', topicHeader: 'Lifestyle', subcategory: 'Sex', insightSubject: 'Expectations around sex', expandedHints: undefined },
  { category: 'Dating', topicHeader: 'Relationship expectations', subcategory: 'Attitudes toward monogamy/polyamory', insightSubject: 'Attitudes toward monogamy/polyamory', expandedHints: undefined },
  { category: 'Dating', topicHeader: 'Personality', subcategory: 'Relationship expectations', insightSubject: 'Independence', expandedHints: undefined },
  { category: 'Dating', topicHeader: 'Lifestyle', subcategory: 'Interests', insightSubject: 'Creative date preferences', expandedHints: undefined },
  { category: 'Dating', topicHeader: 'Lifestyle', subcategory: 'Interests', insightSubject: 'Adventurousness', expandedHints: undefined },
  { category: 'Dating', topicHeader: 'Lifestyle', subcategory: 'Fitness & health', insightSubject: 'Exercise frequency', expandedHints: undefined },
  { category: 'Dating', topicHeader: 'Lifestyle', subcategory: 'Fitness & health', insightSubject: 'Health consciousness', expandedHints: undefined },
  { category: 'Dating', topicHeader: 'Lifestyle', subcategory: 'Food', insightSubject: 'Dietary preferences', expandedHints: undefined },
  { category: 'Dating', topicHeader: 'Lifestyle', subcategory: 'Pets', insightSubject: 'Pet preferences', expandedHints: undefined },
  { category: 'Dating', topicHeader: 'Lifestyle', subcategory: 'Travel', insightSubject: 'Travel frequency', expandedHints: undefined },
  { category: 'Dating', topicHeader: 'Personality', subcategory: 'Humor', insightSubject: 'Sense of humor', expandedHints: undefined },
  { category: 'Dating', topicHeader: 'Personality', subcategory: 'Emotional style', insightSubject: 'Emotional expressiveness', expandedHints: undefined },
  { category: 'Dating', topicHeader: 'Personality', subcategory: 'Communication style', insightSubject: 'Conflict style', expandedHints: undefined },
  { category: 'Dating', topicHeader: 'Personality', subcategory: 'Communication style', insightSubject: 'Listening style', expandedHints: undefined },
  { category: 'Dating', topicHeader: 'Values', subcategory: 'Politics', insightSubject: 'Political orientation', expandedHints: undefined },
  { category: 'Dating', topicHeader: 'Values', subcategory: 'Religion & spirituality', insightSubject: 'Religious beliefs', expandedHints: undefined },
  { category: 'Dating', topicHeader: 'Lifestyle', subcategory: 'Social habits', insightSubject: 'Party frequency', expandedHints: undefined },
  { category: 'Dating', topicHeader: 'Lifestyle', subcategory: 'Social habits', insightSubject: 'Introversion vs extroversion', expandedHints: undefined },
  { category: 'Dating', topicHeader: 'Lifestyle', subcategory: 'Social habits', insightSubject: 'Friend group size preference', expandedHints: undefined },
  { category: 'Dating', topicHeader: 'Lifestyle', subcategory: 'Media', insightSubject: 'Screen time', expandedHints: undefined },
  { category: 'Dating', topicHeader: 'Lifestyle', subcategory: 'Media', insightSubject: 'Favorite genres', expandedHints: undefined },
  { category: 'Dating', topicHeader: 'Lifestyle', subcategory: 'Music', insightSubject: 'Music taste', expandedHints: undefined },
  { category: 'Dating', topicHeader: 'Lifestyle', subcategory: 'Movies & TV', insightSubject: 'Binge-watching habits', expandedHints: undefined },
  { category: 'Dating', topicHeader: 'Lifestyle', subcategory: 'Books', insightSubject: 'Reading frequency', expandedHints: undefined },
  { category: 'Dating', topicHeader: 'Lifestyle', subcategory: 'Art & culture', insightSubject: 'Museum/gallery interest', expandedHints: undefined },
  { category: 'Dating', topicHeader: 'Lifestyle', subcategory: 'Food', insightSubject: 'Cooking frequency', expandedHints: undefined },
  { category: 'Dating', topicHeader: 'Lifestyle', subcategory: 'Food', insightSubject: 'Favorite cuisines', expandedHints: undefined },
  { category: 'Dating', topicHeader: 'Lifestyle', subcategory: 'Fitness & health', insightSubject: 'Morning person vs night owl', expandedHints: undefined },
  { category: 'Dating', topicHeader: 'Lifestyle', subcategory: 'Travel', insightSubject: 'Preferred travel style', expandedHints: undefined },
  { category: 'Dating', topicHeader: 'Personality', subcategory: 'Openness', insightSubject: 'Openness to new experiences', expandedHints: undefined },
  { category: 'Dating', topicHeader: 'Personality', subcategory: 'Conscientiousness', insightSubject: 'Organization style', expandedHints: undefined },
  { category: 'Dating', topicHeader: 'Personality', subcategory: 'Extraversion', insightSubject: 'Energy level', expandedHints: undefined },
  { category: 'Dating', topicHeader: 'Personality', subcategory: 'Agreeableness', insightSubject: 'Kindness level', expandedHints: undefined },
  { category: 'Dating', topicHeader: 'Personality', subcategory: 'Neuroticism', insightSubject: 'Stress management', expandedHints: undefined },
  { category: 'Dating', topicHeader: 'Lifestyle', subcategory: 'Life goals', insightSubject: 'Short-term goals', expandedHints: undefined },
  { category: 'Dating', topicHeader: 'Lifestyle', subcategory: 'Life goals', insightSubject: 'Long-term goals', expandedHints: undefined },
  { category: 'Dating', topicHeader: 'Values', subcategory: 'Family & upbringing', insightSubject: 'Family values', expandedHints: undefined },
  { category: 'Dating', topicHeader: 'Values', subcategory: 'Ethics', insightSubject: 'Moral alignment', expandedHints: undefined },
  { category: 'Dating', topicHeader: 'Lifestyle', subcategory: 'Communication', insightSubject: 'Tone sensitivity', expandedHints: undefined },
  { category: 'Dating', topicHeader: 'Lifestyle', subcategory: 'Personality', insightSubject: 'Trust style', expandedHints: undefined },
  { category: 'Dating', topicHeader: 'Lifestyle', subcategory: 'Lifestyle alignment', insightSubject: 'Routine compatibility', expandedHints: undefined },
]; 