export const CATEGORIES = [
  { category: 'Dating', topicHeader: 'Lifestyle', subcategory: 'Communication', insightSubject: 'Conflict resolution', expandedHints: null },
  { category: 'Dating', topicHeader: 'Lifestyle', subcategory: 'Communication', insightSubject: 'Conversation medium', expandedHints: null },
  { category: 'Dating', topicHeader: 'Lifestyle', subcategory: 'Communication', insightSubject: 'Directness', expandedHints: null },
  { category: 'Dating', topicHeader: 'Personality', subcategory: 'Intention', insightSubject: 'Dating intention', expandedHints: null },
  { category: 'Dating', topicHeader: '', subcategory: 'Romanticism', insightSubject: 'Love language', expandedHints: null },
  { category: 'Dating', topicHeader: 'Lifestyle', subcategory: 'Sex', insightSubject: 'Sex adventurousness', expandedHints: null },
  { category: 'Dating', topicHeader: 'Lifestyle', subcategory: 'Sex', insightSubject: 'Expectations around sex', expandedHints: null },
  { category: 'Dating', topicHeader: 'Personality', subcategory: 'Loyal', insightSubject: 'Attitudes toward monogamy/polyamory', expandedHints: null },
  { category: 'Dating', topicHeader: 'Personality', subcategory: 'Loyal', insightSubject: 'Independence', expandedHints: null },
  { category: 'Dating', topicHeader: 'Personality', subcategory: 'Loyal', insightSubject: 'Relationship Values', expandedHints: null },
  { category: 'Interests', topicHeader: 'Lifestyle', subcategory: 'Shared interests', insightSubject: 'Creative date preferences', expandedHints: null },
  { category: 'Interests', topicHeader: 'Lifestyle', subcategory: 'Shared interests', insightSubject: 'Hobby compatibility', expandedHints: null },
  { category: 'Interests', topicHeader: 'Lifestyle', subcategory: 'Shared interests', insightSubject: 'Gaming compatibility', expandedHints: null },
  { category: 'Interests', topicHeader: 'Lifestyle', subcategory: 'Shared interests', insightSubject: 'Cooking', expandedHints: null },
  { category: 'Interests', topicHeader: 'Lifestyle', subcategory: 'Shared interests', insightSubject: 'Unique interests', expandedHints: null },
  { category: 'Interests', topicHeader: 'Lifestyle', subcategory: 'Intellectual', insightSubject: 'Artistry', expandedHints: null },
  { category: 'Interests', topicHeader: 'Lifestyle', subcategory: 'Intellectual', insightSubject: 'Pastimes', expandedHints: null },
  { category: 'Interests', topicHeader: '', subcategory: 'Entertainment', insightSubject: 'Favorite Movie', expandedHints: null },
  { category: 'Interests', topicHeader: '', subcategory: 'Entertainment', insightSubject: 'Music', expandedHints: null },
  { category: 'Interests', topicHeader: 'Personality', subcategory: 'Adventurous', insightSubject: 'Adventurousness', expandedHints: null },
  { category: 'Interests', topicHeader: 'Personality', subcategory: 'Adventurous', insightSubject: 'Outdoor experiences', expandedHints: null },
  { category: 'Interests', topicHeader: 'Personality', subcategory: 'Adventurous', insightSubject: 'Travel compatibility', expandedHints: null },
  { category: 'Interests', topicHeader: 'Lifestyle', subcategory: 'Fitness', insightSubject: 'Active lifestyle compatibility', expandedHints: null },
  { category: 'Interests', topicHeader: 'Lifestyle', subcategory: 'Fitness', insightSubject: 'Fitness/Sports', expandedHints: null },
  { category: 'Interests', topicHeader: '', subcategory: 'Pets', insightSubject: 'Pet compatibility', expandedHints: null },
  { category: 'Interests', topicHeader: '', subcategory: 'Pets', insightSubject: 'Pet friendliness', expandedHints: null },
  { category: 'Interests', topicHeader: '', subcategory: 'Recreational Drugs', insightSubject: 'Views on recreational drugs', expandedHints: null },
  { category: 'Lifestyle', topicHeader: 'Lifestyle', subcategory: 'Diet', insightSubject: 'Dining compatibility', expandedHints: null },
  { category: 'Lifestyle', topicHeader: 'Lifestyle', subcategory: 'Diet', insightSubject: 'Food preference', expandedHints: null },
  { category: 'Lifestyle', topicHeader: 'Lifestyle', subcategory: 'Diet', insightSubject: 'Dietary restrictions', expandedHints: null },
  { category: 'Lifestyle', topicHeader: '', subcategory: 'Drinking', insightSubject: 'Alcohol consumption', expandedHints: null },
  { category: 'Lifestyle', topicHeader: 'Lifestyle', subcategory: 'Career', insightSubject: 'Career priorities', expandedHints: null },
  { category: 'Lifestyle', topicHeader: 'Lifestyle', subcategory: 'Career', insightSubject: 'Work vibes', expandedHints: null },
  { category: 'Lifestyle', topicHeader: '', subcategory: 'Sleep pattern', insightSubject: 'Daily routine compatibility', expandedHints: null },
  { category: 'Lifestyle', topicHeader: '', subcategory: 'Smoking', insightSubject: 'Smoking', expandedHints: null },
  { category: 'Values', topicHeader: 'Lifestyle', subcategory: 'Money habits', insightSubject: 'Financial tendencies', expandedHints: null },
  { category: 'Values', topicHeader: 'Lifestyle', subcategory: 'Money habits', insightSubject: 'Money talks', expandedHints: null },
  { category: 'Values', topicHeader: '', subcategory: 'Personality', insightSubject: 'Ambition', expandedHints: null },
  { category: 'Values', topicHeader: 'Personality', subcategory: 'Outgoing', insightSubject: 'Extroversion compatibility', expandedHints: null },
  { category: 'Values', topicHeader: '', subcategory: 'Personality', insightSubject: 'Personality', expandedHints: null },
  { category: 'Values', topicHeader: 'Personality', subcategory: 'Organized', insightSubject: 'Organization', expandedHints: null },
  { category: 'Values', topicHeader: '', subcategory: 'Current Family', insightSubject: 'Current family situation', expandedHints: null },
  { category: 'Values', topicHeader: 'Lifestyle', subcategory: 'Family', insightSubject: 'Family planning', expandedHints: null },
  { category: 'Values', topicHeader: 'Lifestyle', subcategory: 'Family', insightSubject: 'Family values', expandedHints: null },
  { category: 'Values', topicHeader: 'Personality', subcategory: 'Political views', insightSubject: 'Political alignment', expandedHints: null },
  { category: 'Values', topicHeader: 'Personality', subcategory: 'Political views', insightSubject: 'Social views', expandedHints: null },
  { category: 'Values', topicHeader: 'Personality', subcategory: 'Political views', insightSubject: 'View on Gender Roles', expandedHints: null },
  { category: 'Values', topicHeader: 'Lifestyle', subcategory: 'Religion', insightSubject: 'Religion', expandedHints: null },
  { category: 'Values', topicHeader: 'Personality', subcategory: 'Open-minded', insightSubject: 'Open-mindedness', expandedHints: null },
  { category: 'Values', topicHeader: 'Personality', subcategory: 'Open-minded', insightSubject: 'Cultural Background', expandedHints: null },
];