export const CATEGORIES = [
  { topic: 'Dating', category: 'Lifestyle', topicHeader: 'Communication', subcategory: 'Conflict resolution', insightSubject: 'Conflict resolution', expandedHints: undefined },
  { topic: 'Dating', category: 'Lifestyle', topicHeader: 'Communication', subcategory: 'Conversation medium', insightSubject: 'Conversation medium', expandedHints: undefined },
  { topic: 'Dating', category: 'Lifestyle', topicHeader: 'Communication', subcategory: 'Directness', insightSubject: 'Directness', expandedHints: undefined },
  { topic: 'Dating', category: 'Lifestyle', topicHeader: 'Communication', subcategory: 'Conversation medium', insightSubject: 'Conversation medium', expandedHints: undefined },
  { topic: 'Dating', category: 'Lifestyle', topicHeader: 'Communication', subcategory: 'Directness', insightSubject: 'Directness', expandedHints: undefined },
  { topic: 'Dating', category: 'Personality', topicHeader: 'Dating expectations', subcategory: 'Dating intention', insightSubject: 'Dating intention', expandedHints: undefined },
  { topic: 'Dating', category: '-', topicHeader: 'Romanticism', subcategory: 'Love language', insightSubject: 'Love language', expandedHints: undefined },
  { topic: 'Dating', category: 'Lifestyle', topicHeader: 'Sex', subcategory: 'Sex adventurousness', insightSubject: 'Sex adventurousness', expandedHints: undefined },
  { topic: 'Dating', category: 'Lifestyle', topicHeader: 'Sex', subcategory: 'Expectations around sex', insightSubject: 'Expectations around sex', expandedHints: undefined },
  { topic: 'Dating', category: 'Relationship expectations', topicHeader: 'Attitudes toward monogamy/polyamory', subcategory: 'Attitudes toward monogamy/polyamory', insightSubject: 'Attitudes toward monogamy/polyamory', expandedHints: undefined },
  { topic: 'Dating', category: 'Personality', topicHeader: 'Relationship expectations', subcategory: 'Independence', insightSubject: 'Independence', expandedHints: undefined },
  { topic: 'Dating', category: 'Lifestyle', topicHeader: 'Interests', subcategory: 'Creative date preferences', insightSubject: 'Creative date preferences', expandedHints: undefined },
  { topic: 'Dating', category: 'Lifestyle', topicHeader: 'Interests', subcategory: 'Adventurousness', insightSubject: 'Adventurousness', expandedHints: undefined },
  { topic: 'Dating', category: 'Lifestyle', topicHeader: 'Fitness & health', subcategory: 'Exercise frequency', insightSubject: 'Exercise frequency', expandedHints: undefined },
  { topic: 'Dating', category: 'Lifestyle', topicHeader: 'Fitness & health', subcategory: 'Health consciousness', insightSubject: 'Health consciousness', expandedHints: undefined },
  { topic: 'Dating', category: 'Lifestyle', topicHeader: 'Food', subcategory: 'Dietary preferences', insightSubject: 'Dietary preferences', expandedHints: undefined },
  { topic: 'Dating', category: 'Lifestyle', topicHeader: 'Pets', subcategory: 'Pet preferences', insightSubject: 'Pet preferences', expandedHints: undefined },
  { topic: 'Dating', category: 'Lifestyle', topicHeader: 'Travel', subcategory: 'Travel frequency', insightSubject: 'Travel frequency', expandedHints: undefined },
  { topic: 'Dating', category: 'Personality', topicHeader: 'Humor', subcategory: 'Sense of humor', insightSubject: 'Sense of humor', expandedHints: undefined },
  { topic: 'Dating', category: 'Personality', topicHeader: 'Emotional style', subcategory: 'Emotional expressiveness', insightSubject: 'Emotional expressiveness', expandedHints: undefined },
  { topic: 'Dating', category: 'Personality', topicHeader: 'Communication style', subcategory: 'Conflict style', insightSubject: 'Conflict style', expandedHints: undefined },
  { topic: 'Dating', category: 'Personality', topicHeader: 'Communication style', subcategory: 'Listening style', insightSubject: 'Listening style', expandedHints: undefined },
  { topic: 'Dating', category: 'Values', topicHeader: 'Politics', subcategory: 'Political orientation', insightSubject: 'Political orientation', expandedHints: undefined },
  { topic: 'Dating', category: 'Values', topicHeader: 'Religion & spirituality', subcategory: 'Religious beliefs', insightSubject: 'Religious beliefs', expandedHints: undefined },
  { topic: 'Dating', category: 'Lifestyle', topicHeader: 'Social habits', subcategory: 'Party frequency', insightSubject: 'Party frequency', expandedHints: undefined },
  { topic: 'Dating', category: 'Lifestyle', topicHeader: 'Social habits', subcategory: 'Introversion vs extroversion', insightSubject: 'Introversion vs extroversion', expandedHints: undefined },
  { topic: 'Dating', category: 'Lifestyle', topicHeader: 'Social habits', subcategory: 'Friend group size preference', insightSubject: 'Friend group size preference', expandedHints: undefined },
  { topic: 'Dating', category: 'Lifestyle', topicHeader: 'Media', subcategory: 'Screen time', insightSubject: 'Screen time', expandedHints: undefined },
  { topic: 'Dating', category: 'Lifestyle', topicHeader: 'Media', subcategory: 'Favorite genres', insightSubject: 'Favorite genres', expandedHints: undefined },
  { topic: 'Dating', category: 'Lifestyle', topicHeader: 'Music', subcategory: 'Music taste', insightSubject: 'Music taste', expandedHints: undefined },
  { topic: 'Dating', category: 'Lifestyle', topicHeader: 'Movies & TV', subcategory: 'Binge-watching habits', insightSubject: 'Binge-watching habits', expandedHints: undefined },
  { topic: 'Dating', category: 'Lifestyle', topicHeader: 'Books', subcategory: 'Reading frequency', insightSubject: 'Reading frequency', expandedHints: undefined },
  { topic: 'Dating', category: 'Lifestyle', topicHeader: 'Art & culture', subcategory: 'Museum/gallery interest', insightSubject: 'Museum/gallery interest', expandedHints: undefined },
  { topic: 'Dating', category: 'Lifestyle', topicHeader: 'Food', subcategory: 'Cooking frequency', insightSubject: 'Cooking frequency', expandedHints: undefined },
  { topic: 'Dating', category: 'Lifestyle', topicHeader: 'Food', subcategory: 'Favorite cuisines', insightSubject: 'Favorite cuisines', expandedHints: undefined },
  { topic: 'Dating', category: 'Lifestyle', topicHeader: 'Fitness & health', subcategory: 'Morning person vs night owl', insightSubject: 'Morning person vs night owl', expandedHints: undefined },
  { topic: 'Dating', category: 'Lifestyle', topicHeader: 'Travel', subcategory: 'Preferred travel style', insightSubject: 'Preferred travel style', expandedHints: undefined },
  { topic: 'Dating', category: 'Personality', topicHeader: 'Openness', subcategory: 'Openness to new experiences', insightSubject: 'Openness to new experiences', expandedHints: undefined },
  { topic: 'Dating', category: 'Personality', topicHeader: 'Conscientiousness', subcategory: 'Organization style', insightSubject: 'Organization style', expandedHints: undefined },
  { topic: 'Dating', category: 'Personality', topicHeader: 'Extraversion', subcategory: 'Energy level', insightSubject: 'Energy level', expandedHints: undefined },
  { topic: 'Dating', category: 'Personality', topicHeader: 'Agreeableness', subcategory: 'Kindness level', insightSubject: 'Kindness level', expandedHints: undefined },
  { topic: 'Dating', category: 'Personality', topicHeader: 'Neuroticism', subcategory: 'Stress management', insightSubject: 'Stress management', expandedHints: undefined },
  { topic: 'Dating', category: 'Lifestyle', topicHeader: 'Life goals', subcategory: 'Short-term goals', insightSubject: 'Short-term goals', expandedHints: undefined },
  { topic: 'Dating', category: 'Lifestyle', topicHeader: 'Life goals', subcategory: 'Long-term goals', insightSubject: 'Long-term goals', expandedHints: undefined },
  { topic: 'Dating', category: 'Values', topicHeader: 'Family & upbringing', subcategory: 'Family values', insightSubject: 'Family values', expandedHints: undefined },
  { topic: 'Dating', category: 'Values', topicHeader: 'Ethics', subcategory: 'Moral alignment', insightSubject: 'Moral alignment', expandedHints: undefined },
  { topic: 'Dating', category: 'Lifestyle', topicHeader: 'Communication', subcategory: 'Tone sensitivity', insightSubject: 'Tone sensitivity', expandedHints: undefined },
  { topic: 'Dating', category: 'Lifestyle', topicHeader: 'Personality', subcategory: 'Trust style', insightSubject: 'Trust style', expandedHints: undefined },
  { topic: 'Dating', category: 'Lifestyle', topicHeader: 'Lifestyle alignment', subcategory: 'Routine compatibility', insightSubject: 'Routine compatibility', expandedHints: undefined },
]; 